from flask import Flask,render_template,request
import tensorflow as tf
from keras.models import load_model
from keras.preprocessing import image
import warnings
import base64
import numpy as np
from PIL import Image
import io



warnings.filterwarnings('ignore')


class_names_dict = {
    0:'Apple scab',
    1:'Apple Black rot',
    2:'Apple Cedar rust',
    3: 'Apple healthy',
    4:'Blueberry healthy',
    5: 'Cherry (including sour) Powdery mildew',
    6:'Cherry (including sour) healthy', 
    7:'Corn (maize) Cercospora leaf spot Gray leaf spot',
    8: 'Corn (maize) Common rust',
    9:'Corn (maize) Northern Leaf Blight',
    10:'Corn (maize) healthy',
    11:'Grape Black rot',
    12:'Grape Esca (Black Measles)',
    13: 'Grape Leaf blight (Isariopsis Leaf Spot)',
    14:'Grape healthy',
    15:'Orange Haunglongbing (Citrus greening)',
    16:'Peach Bacterial spot',
    17: 'Peach healthy',
    18:'Pepper, bell Bacterial spot',
    19:'Pepper, bell healthy',
    20:'Potato Early blight',
    21:'Potato Late blight',
    22:'Potato healthy',
    23:'Raspberry healthy',
    24: 'Soybean healthy',
    25: 'Squash Powdery mildew',
    26: 'Strawberry Leaf scorch',
    27: 'Strawberry healthy',
    28: 'Tomato Bacterial spot',
    29: 'Tomato Early blight',
    30: 'Tomato Late blight',
    31: 'Tomato Leaf Mold',
    32: 'Tomato Septoria leaf spot',
    33: 'Tomato Spider mites Two-spotted spider mite',
    34:'Tomato Target Spot',
    35: 'Tomato Yellow Leaf Curl Virus',
    36: 'Tomato mosaic virus',
    37: 'Tomato healthy'
}


resnet_model = load_model('ResNet50_model.h5',compile=False)
resnet_model.make_predict_function()        


def prediction(img_path):
    img = image.load_img(img_path, target_size=(256,256))
    img = image.img_to_array(img)
    img = img.reshape(1,256,256,3)
    pred = resnet_model.predict(img)
    pred = tf.argmax(pred,axis=1)
    pred_value = pred.numpy()[0]
    return pred_value


app=Flask(__name__)

app.static_folder = 'static'


'''def predict(image_data):
    return "healthy"



@app.route('/predict', methods=['POST'])
def predict_image():
    image_data = request.json.get('image')
    # Decode base64 image data
    image_bytes = base64.b64decode(image_data.split(',')[1])
    # Convert bytes to PIL image
    image = Image.open(io.BytesIO(image_bytes))
    # Perform any necessary preprocessing here
    # Example: resize image, convert to grayscale, etc.
    # Make prediction
    prediction = predict(image)
    return jsonify({'prediction': prediction})
'''


@app.route('/')
def home():
    return render_template('index.html',**locals())

@app.route('/predict' , methods = ['GET','POST'])
def predict():
    if request.method == 'POST':
        input_image = request.files['input_image']
        
        img_path = "static/"+ input_image.filename
        input_image.save(img_path)

        result = prediction(img_path)
        
        result = class_names_dict.get(result)
        intro = ''
        treatment = ''
        if result=='Apple scab' :
            intro = intro.join('''Apple scab, caused by the fungus Venturia inaequalis, is one of 
            the most devastating diseases affecting apple trees worldwide. Characterized by dark, scabby lesions on 
            leaves, fruit, and twigs, this fungal infection not only compromises the aesthetic appeal of apples but also 
            diminishes yield and quality. It thrives in cool, wet conditions, making orchards particularly vulnerable during 
            rainy seasons. Apple scab can lead to defoliation, reduced fruit size, and premature fruit drop, posing significant 
            economic challenges for growers. Management strategies typically involve cultural practices, such as sanitation and 
            fungicide applications, alongside resistant apple cultivars to mitigate the impact of this persistent pathogen.''')
            treatment = treatment.join('''Managing apple scab involves a multifaceted approach. Cultural practices such as maintaining proper 
            orchard hygiene by removing infected leaves and fruit debris can help reduce the spread of the fungus. Regular 
            applications of fungicides, particularly during periods of high disease pressure, are essential for controlling the 
            disease. Additionally, planting resistant apple varieties can provide long-term protection against apple scab. Integrated
            pest management techniques, including monitoring weather conditions and implementing timely treatments, 
            play a crucial role in minimizing the impact of this persistent disease on apple orchards.''')
        elif result =='Apple Cedar rust':
            intro = intro.join('''Apple Black Rot disease, caused by the fungus Botryosphaeria obtusa, is a significant threat to apple orchards worldwide. Characterized by dark, sunken lesions on fruit, leaves, and twigs, this disease not only diminishes fruit quality but also leads to substantial yield losses. The fungus overwinters in infected plant debris and spreads during periods of high humidity and rainfall, making effective management challenging. Cultural practices such as sanitation and proper pruning, along with fungicide applications, are crucial for controlling the spread of Apple Black Rot and safeguarding orchard productivity.''')
            treatment = treatment.join('''Managing Apple Black Rot disease requires a multifaceted approach involving both cultural and chemical strategies. Effective measures include thorough orchard sanitation to remove infected plant debris, proper pruning to improve airflow and sunlight penetration, and timely application of fungicides during critical periods of disease development. Additionally, employing resistant apple cultivars and implementing integrated pest management practices can help mitigate the spread of the fungus. Regular monitoring of orchards for early signs of infection and prompt action are essential for minimizing the impact of Apple Black Rot and preserving apple yields and quality.''')
        elif result == 'Apple Black rot':
            intro = intro.join('''Apple cedar rust disease, caused by the fungal pathogen Gymnosporangium juniperi-virginianae, poses a significant threat to apple orchards worldwide. This disease cycles between apple trees and certain species of juniper, such as red cedar, completing its life cycle and causing distinctive symptoms on both hosts. Infected apple trees exhibit yellow-orange spots on leaves and fruit, leading to defoliation and reduced fruit quality. Control measures often involve fungicide applications and cultural practices to manage juniper hosts, highlighting the complex management challenges posed by this pervasive pathogen.''')
            treatment = treatment.join('''Managing apple cedar rust disease involves a combination of cultural practices and chemical control methods. These include planting resistant apple cultivars, removing nearby juniper hosts, pruning to improve airflow and reduce humidity, and applying fungicides according to a targeted spray schedule. Integrated pest management strategies, including monitoring for disease symptoms and adjusting control measures accordingly, are crucial for effectively managing and minimizing the impact of this disease on apple orchards.''')
        elif result == 'Apple healthy':
            intro = intro.join('There is no diseae in your plant or crop')
            treatment = treatment.join('''Ensuring the health and vitality of plants and crops is paramount for agricultural success. Through a holistic approach that integrates both traditional and innovative methods, we aim to optimize plant growth and resilience. Our treatment regimen begins with soil analysis to determine nutrient deficiencies and pH levels, followed by tailored fertilization strategies. Implementing organic practices, such as composting and crop rotation, enriches soil structure and minimizes reliance on synthetic inputs. We also emphasize pest and disease management through natural predators, companion planting, and eco-friendly sprays. Embracing cutting-edge technologies like precision irrigation and genetic engineering for disease resistance further fortifies our commitment to sustainable agriculture, fostering not only healthier plants but also a thriving ecosystem.''')
        elif result == 'Blueberry healthy':
            intro = intro.join('There is no diseae in your plant or crop')
            treatment = treatment.join('''Ensuring the health and vitality of plants and crops is paramount for agricultural success. Through a holistic approach that integrates both traditional and innovative methods, we aim to optimize plant growth and resilience. Our treatment regimen begins with soil analysis to determine nutrient deficiencies and pH levels, followed by tailored fertilization strategies. Implementing organic practices, such as composting and crop rotation, enriches soil structure and minimizes reliance on synthetic inputs. We also emphasize pest and disease management through natural predators, companion planting, and eco-friendly sprays. Embracing cutting-edge technologies like precision irrigation and genetic engineering for disease resistance further fortifies our commitment to sustainable agriculture, fostering not only healthier plants but also a thriving ecosystem.''')
        elif result == 'Cherry (including sour) Powdery mildew':
            intro = intro.join('''Cherry trees, renowned for their luscious fruits, face a formidable foe in the form of powdery mildew disease, a fungal infection that can devastate their delicate foliage. Characterized by a powdery white coating on leaves, stems, and buds, this affliction thrives in warm, dry conditions, posing a particular threat to sour cherry varieties. As the fungus spreads, it inhibits photosynthesis and weakens the tree's ability to produce fruit, ultimately jeopardizing harvest yields. Mitigation strategies, such as proper pruning and fungicidal treatments, are crucial to safeguarding cherry orchards against this pervasive menace.''')
            treatment = treatment.join('''Combatting powdery mildew disease in cherry trees requires a multifaceted approach aimed at reducing fungal spread and bolstering tree health. Cultural practices such as adequate spacing between trees to promote airflow, regular pruning to remove infected plant parts, and thorough sanitation by clearing fallen leaves can help mitigate its spread. Additionally, applying fungicidal treatments early in the growing season, especially during periods of high humidity, can effectively manage the disease. Incorporating disease-resistant cherry varieties and monitoring weather conditions can further enhance prevention efforts. By combining these strategies, growers can minimize the impact of powdery mildew and protect their cherry crops.''')
        elif result == 'Corn (maize) Cercospora leaf spot Gray leaf spot':
            intro = intro.join('''Corn, commonly known as maize, is one of the most vital cereal crops globally, serving as a staple food for millions. However, its cultivation faces significant challenges, including the threat of fungal diseases like Cercospora leaf spot and Gray leaf spot. Cercospora leaf spot, caused by the fungus Cercospora zeae-maydis, manifests as small, dark brown lesions surrounded by a yellow halo on the leaves, eventually leading to premature leaf death and reduced photosynthetic capacity. On the other hand, Gray leaf spot disease, caused by the fungus Cercospora zeae-maydis, presents as small, rectangular lesions with gray centers and brown borders, spreading rapidly under warm and humid conditions. Both diseases pose substantial economic risks to corn production worldwide, emphasizing the importance of effective management strategies to mitigate their impact and ensure global food security.''')
            treatment = treatment.join('''Combatting powdery mildew disease in cherry trees requires a multifaceted approach aimed at reducing fungal spread and bolstering tree health. Cultural practices such as adequate spacing between trees to promote airflow, regular pruning to remove infected plant parts, and thorough sanitation by clearing fallen leaves can help mitigate its spread. Additionally, applying fungicidal treatments early in the growing season, especially during periods of high humidity, can effectively manage the disease. Incorporating disease-resistant cherry varieties and monitoring weather conditions can further enhance prevention efforts. By combining these strategies, growers can minimize the impact of powdery mildew and protect their cherry crops.''')
        elif result == 'Corn (maize) Common rust':
            intro = intro.join('''Corn, also known as maize, is one of the most widely cultivated cereal crops globally, serving as a staple food for many nations and a vital component in various industries, including animal feed, ethanol production, and food processing. However, corn crops face numerous challenges, among which is the prevalent threat of common rust disease. Common rust, caused by the fungus Puccinia sorghi, manifests as small, reddish-brown pustules on the leaves, stems, and husks of the corn plant. While rarely causing severe damage, common rust can diminish yields if left unchecked, making it a concern for corn farmers worldwide. Effective management strategies, including fungicide applications and crop rotation, are crucial for mitigating the impact of common rust and maintaining the productivity of corn crops.''')
            treatment = treatment.join('''Managing common rust disease in corn involves a combination of cultural practices, genetic resistance, and chemical control. Implementing crop rotation with non-host plants, such as soybeans or wheat, can help reduce the buildup of the fungus in the soil. Planting resistant corn varieties is also essential, as they can limit the severity of the disease. Additionally, timely application of fungicides, especially during periods of high humidity and warm temperatures, can effectively suppress rust development. Regular scouting and monitoring of corn fields are crucial for early detection of the disease, allowing for prompt intervention to minimize yield losses.''')
        elif result == 'Corn (maize) Northern Leaf Blight':
            intro = intro.join('''Northern Leaf Blight (NLB) is a devastating fungal disease that affects corn (maize) plants, primarily caused by the pathogen Setosphaeria turcica. Characterized by its distinctive elongated lesions with wavy edges on the leaves, NLB can significantly impair photosynthesis and ultimately reduce yield potential. The disease thrives in cool, humid conditions, making it particularly problematic in regions with temperate climates. NLB not only diminishes crop quality but also renders plants more susceptible to other stressors, exacerbating agricultural challenges. Effective management strategies, including crop rotation, fungicide application, and utilization of resistant varieties, are crucial for mitigating the impact of Northern Leaf Blight and ensuring the productivity and resilience of corn crops.''')
            treatment = treatment.join('''Managing Northern Leaf Blight (NLB) in corn involves a combination of cultural practices and chemical control methods. Crop rotation with non-host plants can disrupt the disease cycle, while planting resistant varieties can offer effective long-term control. Additionally, timely application of fungicides during periods of high disease pressure can help suppress NLB outbreaks. Proper field sanitation, including removal of crop debris after harvest, is essential to reduce overwintering inoculum. Integrated pest management (IPM) approaches, such as scouting for early signs of infection and implementing preventative measures, are crucial for sustainable NLB management while minimizing environmental impact and preserving crop yield potential''')
        elif result=='Corn (maize) healthy':
            intro = intro.join('''Ensuring the health and vitality of plants and crops is paramount for agricultural success. Through a holistic approach that integrates both traditional and innovative methods, we aim to optimize plant growth and resilience. Our treatment regimen begins with soil analysis to determine nutrient deficiencies and pH levels, followed by tailored fertilization strategies. Implementing organic practices, such as composting and crop rotation, enriches soil structure and minimizes reliance on synthetic inputs. We also emphasize pest and disease management through natural predators, companion planting, and eco-friendly sprays. Embracing cutting-edge technologies like precision irrigation and genetic engineering for disease resistance further fortifies our commitment to sustainable agriculture, fostering not only healthier plants but also a thriving ecosystem.''')
        elif result == 'Grape Black rot':
            intro = intro.join('''Grape Black Rot, caused by the fungus Guignardia bidwellii, is a devastating disease affecting grapevines worldwide. Characterized by distinctive black lesions on leaves, fruit, and stems, it thrives in warm, humid climates, spreading rapidly during periods of high moisture. The disease compromises grape quality and yield, leading to significant economic losses for vineyard owners. Effective management strategies typically involve a combination of cultural practices, fungicides, and resistant grape varieties to mitigate its impact.''')
            treatment = treatment.join('''Managing Grape Black Rot requires an integrated approach combining cultural practices, chemical control, and, where available, resistant grape varieties. Cultural practices involve diligent sanitation measures, such as removing and destroying infected plant material, to minimize disease spread. Additionally, ensuring proper vineyard canopy management to improve air circulation and reduce humidity can inhibit fungal growth. Chemical control involves timely application of fungicides, particularly during critical stages of grape development, following recommended dosage and application schedules. Utilizing resistant grape varieties, if feasible, offers long-term sustainability by reducing reliance on fungicides. Regular monitoring of vineyards for early signs of infection and swift intervention are crucial components of an effective disease management strategy.''')
        elif result == 'Grape Esca (Black Measles)':
            intro = intro.join('''Grape Esca, commonly known as Black Measles, is a devastating fungal disease that affects grapevines worldwide, causing significant economic losses in the wine industry. It manifests through characteristic black streaks in the wood, leaf discoloration, and premature defoliation, ultimately leading to reduced yield and quality of grapes. Esca is caused by various fungi, primarily Phaeomoniella chlamydospora and Phaeoacremonium spp., which infect the vines through wounds and pruning cuts. Despite efforts to manage the disease through cultural practices and fungicide applications, Esca remains a persistent challenge for grape growers, highlighting the need for ongoing research and development of effective control strategies.''')
            treatment = treatment.join('''Managing Grape Esca involves a combination of preventative measures and cultural practices. Pruning techniques that minimize wounds, such as double pruning or using wound protectants, can reduce infection rates. Additionally, maintaining vineyard hygiene by removing infected wood and promptly disposing of it helps limit the spread of the disease. Some growers also employ fungicides, although their efficacy can vary. Genetic resistance in grape varieties is being explored as a long-term solution. Overall, an integrated approach that combines cultural, chemical, and potentially genetic strategies is crucial for effectively managing Grape Esca and mitigating its impact on vineyard productivity and grape quality.''')
        elif result == 'Grape Leaf blight (Isariopsis Leaf Spot)':
            intro = intro.join('''Grape leaf blight, also known as Isariopsis leaf spot, is a fungal disease that affects grapevines, causing significant damage to foliage and potentially reducing yields. The pathogen responsible for this disease, Isariopsis spp., thrives in warm, humid conditions, making it particularly problematic in regions with such climates. Infected grape leaves develop characteristic small, circular lesions with dark brown centers and yellow halos, eventually leading to defoliation if left untreated. Severe outbreaks can weaken vines, making them more susceptible to other diseases and environmental stresses. Control measures typically involve cultural practices such as pruning to improve air circulation, fungicide applications, and planting disease-resistant grape varieties. Early detection and prompt management are crucial in minimizing the impact of grape leaf blight on vine health and fruit quality.''')
            treatment = treatment.join('''Managing grape leaf blight involves a combination of cultural practices and chemical control methods. Pruning to increase airflow and sunlight penetration, as well as maintaining proper vineyard sanitation by removing infected plant material, can help reduce disease spread. Application of fungicides, particularly during periods of high disease pressure, is also essential. Choosing resistant grape varieties and implementing integrated pest management strategies can further aid in preventing and controlling Isariopsis leaf spot. Regular monitoring and early intervention are key to effectively managing this disease and safeguarding grapevine health.''')
        elif result == 'Orange Haunglongbing (Citrus greening)':
            intro = intro.join('''Orange Huanglongbing, commonly known as citrus greening, is a devastating bacterial disease that poses a significant threat to citrus trees worldwide, particularly oranges. Caused by the bacterium Candidatus Liberibacter asiaticus, it spreads through insect vectors and affects the tree's vascular system, leading to symptoms such as yellowing leaves, misshapen and bitter fruit, and ultimately tree decline. This disease not only causes immense economic losses to citrus growers but also undermines the citrus industry's sustainability and food security. Efforts to control and manage citrus greening involve a combination of measures including insecticide treatments, cultural practices, and ongoing research into resistant cultivars and disease management strategies.''')
            treatment = treatment.join('''Dealing with Orange Huanglongbing (Citrus greening) involves a multifaceted approach. Integrated pest management strategies, including the use of insecticides to control the vector, such as the Asian citrus psyllid, are crucial. Cultural practices like pruning infected branches and removing infected trees help mitigate its spread. Additionally, research into resistant citrus varieties and biological control methods offers long-term solutions. Collaborative efforts among growers, researchers, and government agencies are essential to combat this disease effectively and sustain the citrus industry.''')
        elif result == 'Peach Bacterial spot':
            intro = intro.join('''Peach Bacterial Spot, caused by the pathogen Xanthomonas arboricola pv. pruni, is a significant disease affecting peach trees worldwide. This highly contagious bacterium primarily targets the leaves, fruit, and stems, manifesting as dark, water-soaked lesions with raised margins. These lesions can lead to premature defoliation, reduced fruit quality, and even tree death under severe infections. Management strategies often involve a combination of cultural practices, such as sanitation and pruning, along with chemical control methods, although resistant varieties offer promising long-term solutions. Nonetheless, the constant threat of this disease underscores the importance of vigilant monitoring and proactive management within peach orchards.''')
            treatment = treatment.join('''Managing Peach Bacterial Spot involves a holistic approach combining cultural, biological, and chemical control methods. Implementing strict sanitation practices, such as removing infected plant debris, pruning to improve air circulation, and avoiding overhead irrigation, helps reduce disease pressure. Biological control agents, like antagonistic bacteria or copper-based fungicides, can suppress bacterial populations. Additionally, applying bactericides before symptoms appear, following label instructions meticulously, and rotating chemistries to prevent resistance development are crucial chemical control measures. Incorporating disease-resistant peach cultivars into orchards can provide long-term sustainable solutions. Regular monitoring for early detection and prompt action further enhance control efforts, ultimately mitigating the impact of Peach Bacterial Spot on orchard productivity and profitability.''')
        
        elif result == 'Peach healthy':
            intro = intro.join('There is no diseae in your plant or crop')
            treatment = treatment.join('''Ensuring the health and vitality of plants and crops is paramount for agricultural success. Through a holistic approach that integrates both traditional and innovative methods, we aim to optimize plant growth and resilience. Our treatment regimen begins with soil analysis to determine nutrient deficiencies and pH levels, followed by tailored fertilization strategies. Implementing organic practices, such as composting and crop rotation, enriches soil structure and minimizes reliance on synthetic inputs. We also emphasize pest and disease management through natural predators, companion planting, and eco-friendly sprays. Embracing cutting-edge technologies like precision irrigation and genetic engineering for disease resistance further fortifies our commitment to sustainable agriculture, fostering not only healthier plants but also a thriving ecosystem.''')        
        
        elif result == 'Pepper, bell Bacterial spot':
            intro = intro.join('''Pepper, a staple in cuisines worldwide, is a versatile vegetable cherished for its vibrant colors and distinctive flavor. However, pepper plants are susceptible to various diseases, among which bacterial spot stands out as a significant threat. This bacterial infection, caused by Xanthomonas campestris pv. vesicatoria, manifests as dark, water-soaked lesions on leaves, stems, and fruits, ultimately leading to reduced yield and quality. Bacterial spot not only compromises the economic viability of pepper cultivation but also necessitates vigilant management practices to mitigate its impact and safeguard pepper crops.''')
            treatment = treatment.join('''Managing bacterial spot in pepper plants requires an integrated approach. Implementing cultural practices such as crop rotation, proper irrigation management to minimize leaf wetness, and sanitation measures like removing infected plant debris can help reduce the disease's spread. Additionally, applying copper-based fungicides or bactericides can effectively suppress bacterial populations. Regular monitoring for early symptoms and timely intervention are crucial for effectively controlling bacterial spot and preserving pepper crop health.''')
        
        elif result == 'Pepper, bell healthy':
            intro = intro.join('There is no diseae in your plant or crop')
            treatment = treatment.join('''Ensuring the health and vitality of plants and crops is paramount for agricultural success. Through a holistic approach that integrates both traditional and innovative methods, we aim to optimize plant growth and resilience. Our treatment regimen begins with soil analysis to determine nutrient deficiencies and pH levels, followed by tailored fertilization strategies. Implementing organic practices, such as composting and crop rotation, enriches soil structure and minimizes reliance on synthetic inputs. We also emphasize pest and disease management through natural predators, companion planting, and eco-friendly sprays. Embracing cutting-edge technologies like precision irrigation and genetic engineering for disease resistance further fortifies our commitment to sustainable agriculture, fostering not only healthier plants but also a thriving ecosystem.''')

        elif result == 'Potato Early blight':
            intro = intro.join('''Potato early blight, caused by the fungus Alternaria solani, is a common and destructive foliar disease affecting potato crops worldwide. Characterized by the appearance of dark lesions on the leaves, early blight primarily thrives in warm, humid conditions, making it prevalent during the growing season in many potato-producing regions. The disease not only reduces yield but also compromises tuber quality, posing significant economic challenges for farmers. Integrated management strategies involving cultural practices, resistant cultivars, and fungicidal applications are typically employed to mitigate its impact, highlighting the importance of proactive measures in potato cultivation.''')
            treatment = treatment.join('''Managing Potato Early blight requires a multifaceted approach including crop rotation, sanitation, and fungicide applications. Utilizing resistant potato cultivars, maintaining proper spacing to promote air circulation, and removing infected plant debris can help reduce disease pressure. Additionally, timely application of fungicides, adhering to recommended schedules, can effectively control early blight outbreaks. Integrating these strategies in a comprehensive management plan is essential for minimizing yield losses and maintaining potato crop health.''')
        elif result == 'Potato Late blight':
            intro = intro.join('''Potato late blight, caused by the pathogen Phytophthora infestans, is one of the most devastating diseases affecting potato crops worldwide. This destructive plant disease can rapidly spread under favorable conditions, leading to significant yield losses and economic impacts for farmers. Late blight manifests as dark lesions on leaves, stems, and tubers, ultimately causing plant defoliation and rotting of potatoes. Its ability to survive in soil and plant debris poses challenges for control measures, often necessitating the use of fungicides and resistant potato varieties. Effective management strategies, including crop rotation and early detection, are crucial for mitigating the impact of potato late blight on agricultural productivity and food security.''')
            treatment = treatment.join('''Effective management of potato late blight involves a combination of cultural practices, chemical control, and the use of resistant potato varieties. Crop rotation with non-host plants can disrupt the disease cycle, while timely application of fungicides can suppress pathogen spread. Planting resistant potato cultivars can also reduce susceptibility to the disease. Additionally, monitoring for early signs of infection and implementing strict sanitation measures, such as removing infected plant debris, are essential for preventing the spread of late blight within and between growing seasons.''')
        
        
        elif result == 'Potato healthy':
            intro = intro.join('There is no diseae in your plant or crop')
            treatment = treatment.join('''Ensuring the health and vitality of plants and crops is paramount for agricultural success. Through a holistic approach that integrates both traditional and innovative methods, we aim to optimize plant growth and resilience. Our treatment regimen begins with soil analysis to determine nutrient deficiencies and pH levels, followed by tailored fertilization strategies. Implementing organic practices, such as composting and crop rotation, enriches soil structure and minimizes reliance on synthetic inputs. We also emphasize pest and disease management through natural predators, companion planting, and eco-friendly sprays. Embracing cutting-edge technologies like precision irrigation and genetic engineering for disease resistance further fortifies our commitment to sustainable agriculture, fostering not only healthier plants but also a thriving ecosystem.''')
            
        elif result == 'Raspberry healthy':
            intro = intro.join('There is no diseae in your plant or crop')
            treatment = treatment.join('''Ensuring the health and vitality of plants and crops is paramount for agricultural success. Through a holistic approach that integrates both traditional and innovative methods, we aim to optimize plant growth and resilience. Our treatment regimen begins with soil analysis to determine nutrient deficiencies and pH levels, followed by tailored fertilization strategies. Implementing organic practices, such as composting and crop rotation, enriches soil structure and minimizes reliance on synthetic inputs. We also emphasize pest and disease management through natural predators, companion planting, and eco-friendly sprays. Embracing cutting-edge technologies like precision irrigation and genetic engineering for disease resistance further fortifies our commitment to sustainable agriculture, fostering not only healthier plants but also a thriving ecosystem.''')
        
        elif result == 'Soybean healthy':
            intro = intro.join('There is no diseae in your plant or crop')
            treatment = treatment.join('''Ensuring the health and vitality of plants and crops is paramount for agricultural success. Through a holistic approach that integrates both traditional and innovative methods, we aim to optimize plant growth and resilience. Our treatment regimen begins with soil analysis to determine nutrient deficiencies and pH levels, followed by tailored fertilization strategies. Implementing organic practices, such as composting and crop rotation, enriches soil structure and minimizes reliance on synthetic inputs. We also emphasize pest and disease management through natural predators, companion planting, and eco-friendly sprays. Embracing cutting-edge technologies like precision irrigation and genetic engineering for disease resistance further fortifies our commitment to sustainable agriculture, fostering not only healthier plants but also a thriving ecosystem.''')

        elif result == 'Squash Powdery mildew':
            intro = intro.join('''Squash powdery mildew, caused by the fungal pathogen Podosphaera xanthii, is a common and troublesome disease affecting squash plants worldwide. Characterized by a white, powdery growth on the leaves, stems, and fruits, this fungal infection can severely impair photosynthesis, leading to stunted growth, reduced yields, and even plant death if left untreated. Powdery mildew thrives in warm, dry conditions and can spread rapidly, particularly in crowded plantings. Effective management strategies often involve cultural practices, such as adequate spacing between plants, proper irrigation, and the use of resistant varieties, along with timely application of fungicides when necessary.''')
            treatment = treatment.join('''To effectively manage squash powdery mildew, a combination of cultural practices and targeted treatments is key. Begin by ensuring proper plant spacing to promote air circulation, which helps reduce humidity levels that favor fungal growth. Additionally, avoid overhead watering to minimize moisture on foliage. Regularly inspect plants for early signs of infection, such as white powdery spots, and promptly remove affected leaves to prevent further spread. Utilizing resistant squash varieties can also offer protection against the disease. If powdery mildew persists, consider applying fungicides approved for use on squash, following label instructions carefully to ensure safe and effective application. Implementing these integrated pest management techniques can help mitigate the impact of squash powdery mildew and preserve plant health and productivity.''')
        elif result == 'Strawberry Leaf scorch':
            treatment = treatment.join('''Strawberry leaf scorch, caused by the fungal pathogen Diplocarpon earlianum, is a significant concern for strawberry growers worldwide. This disease manifests as dark, irregular lesions on the leaves, often leading to browning, drying, and eventual defoliation. In addition to its aesthetic impact, strawberry leaf scorch can severely impair photosynthesis and reduce fruit yield. Management strategies typically involve a combination of cultural practices, such as crop rotation and sanitation, along with the judicious use of fungicides to mitigate its spread and impact on strawberry crops.''')
            treatment = treatment.join('''Managing Strawberry leaf scorch involves a multifaceted approach including regular inspection and removal of infected plant material, promoting good air circulation through proper spacing and pruning, maintaining soil moisture levels to prevent excessive wetness, and applying fungicides as necessary according to integrated pest management protocols. Additionally, employing resistant strawberry varieties and practicing crop rotation can help reduce the incidence and severity of the disease over time.''')
        
        elif result == 'Strawberry healthy':
            intro = intro.join('There is no disease in your plant or crop')
            treatment = treatment.join('''Ensuring the health and vitality of plants and crops is paramount for agricultural success. Through a holistic approach that integrates both traditional and innovative methods, we aim to optimize plant growth and resilience. Our treatment regimen begins with soil analysis to determine nutrient deficiencies and pH levels, followed by tailored fertilization strategies. Implementing organic practices, such as composting and crop rotation, enriches soil structure and minimizes reliance on synthetic inputs. We also emphasize pest and disease management through natural predators, companion planting, and eco-friendly sprays. Embracing cutting-edge technologies like precision irrigation and genetic engineering for disease resistance further fortifies our commitment to sustainable agriculture, fostering not only healthier plants but also a thriving ecosystem.''')

        elif result == 'Tomato Bacterial spot':
            intro = intro.join('''Tomato Bacterial spot is a destructive disease caused by the bacterium Xanthomonas campestris pv. vesicatoria, impacting tomato plants worldwide. Characterized by small, dark lesions on leaves, stems, and fruits, it can lead to defoliation, reduced fruit quality, and significant yield loss. The bacterium spreads through infected seeds, plant debris, and splashing water, thriving in warm, humid conditions. Management strategies often involve cultural practices, such as crop rotation and sanitation, alongside chemical treatments, but prevention through resistant varieties remains a key approach in mitigating its impact on tomato cultivation.''')
            treatment = treatment.join('''Managing Tomato Bacterial spot involves a combination of cultural practices and chemical treatments. Employing crop rotation, sanitation, and avoiding overhead irrigation can help reduce the spread of the disease. Additionally, applying copper-based fungicides or bactericides during the early stages of infection can suppress bacterial growth. Choosing resistant tomato varieties and promptly removing infected plants further contribute to effective management strategies, ultimately minimizing yield losses and preserving tomato crop health.''')
        elif result == 'Tomato Early blight':
            intro = intro.join('''Tomato early blight, caused by the fungus Alternaria solani, is a prevalent and economically significant disease affecting tomato plants worldwide. Characterized by dark, concentric lesions on leaves, stems, and fruits, early blight can lead to defoliation, reduced yield, and overall plant decline. Favorable conditions for its development include warm temperatures, high humidity, and poor air circulation. Management strategies typically involve cultural practices such as crop rotation, sanitation, and fungicide application, although resistant cultivars are also being developed to combat this persistent threat to tomato production.''')
            treatment = treatment.join('''Managing tomato early blight involves a combination of cultural and chemical strategies. Implementing crop rotation, ensuring proper spacing between plants for adequate air circulation, and regularly removing infected plant debris can help reduce the disease's spread. Additionally, applying fungicides preventatively or at the first signs of infection can effectively suppress the fungus. Opting for resistant tomato cultivars and maintaining overall plant health through balanced nutrition and watering practices can further bolster the plant's ability to withstand early blight. Regular monitoring and prompt action are essential for successful management of this disease.''')
        elif result == 'Tomato Late blight':
            intro = intro.join('''Tomato late blight, caused by the pathogen Phytophthora infestans, is a devastating fungal disease that affects tomatoes worldwide. Characterized by dark, water-soaked lesions on leaves, stems, and fruits, late blight thrives in cool, wet conditions, making it particularly problematic in regions with high humidity and frequent rainfall. It spreads rapidly, facilitated by wind, rain, and infected plant material, leading to significant yield losses if left unchecked. Historically infamous for triggering the Irish Potato Famine in the 1840s, late blight remains a constant threat to tomato crops, necessitating vigilant monitoring, timely intervention with fungicides, and cultivation of resistant varieties to mitigate its impact on agricultural productivity.''')
            treatment = treatment.join('''To effectively manage Tomato late blight, a combination of cultural practices, preventative measures, and chemical control is essential. Employing crop rotation, ensuring proper spacing between plants for adequate air circulation, and timely removal of infected plant material can help reduce disease pressure. Additionally, applying fungicides preventatively, especially during periods of high humidity and rainfall, can suppress the spread of the pathogen. Incorporating resistant tomato varieties into cultivation practices further strengthens defenses against late blight. Regular scouting and early detection of symptoms enable prompt action, enhancing the likelihood of successful disease management.''')
        elif result == 'Tomato Leaf Mold':
            intro = intro.join('''Tomato leaf mold, caused by the fungus Passalora fulva (formerly known as Fulvia fulva), is a common disease affecting tomato plants worldwide. It manifests as yellowish or brown patches on the upper surface of tomato leaves, often accompanied by a fuzzy, velvety growth on the underside. This mold thrives in warm and humid conditions, spreading rapidly in greenhouse environments or during periods of high moisture. While not typically fatal to the plant, severe infestations can lead to defoliation, reduced fruit yield, and diminished plant vigor. Effective management strategies include maintaining proper air circulation, practicing crop rotation, and applying fungicides as necessary.''')
            treatment = treatment.join('''To effectively manage tomato leaf mold, implement cultural practices such as spacing plants adequately for air circulation, avoiding overhead watering, and removing infected leaves promptly. Additionally, employ preventive measures like applying fungicides containing chlorothalonil or copper-based compounds, ensuring thorough coverage of foliage. Organic alternatives like neem oil or potassium bicarbonate can also help suppress the disease. Regularly inspect plants for symptoms, and if necessary, consider resistant tomato varieties for future plantings.''')
        elif result == 'Tomato Septoria leaf spot':
            intro = intro.join('''Tomato Septoria leaf spot, caused by the fungus Septoria lycopersici, is a common and widespread disease affecting tomato plants globally. Characterized by small, dark spots with lighter centers on the lower leaves, it gradually spreads upwards, eventually leading to defoliation and reduced fruit yield. Favoring warm and humid conditions, the fungus overwinters in plant debris and soil, thriving in environments where sanitation practices are lacking. Control measures often involve a combination of cultural practices such as crop rotation, proper spacing, and fungicide applications to manage the disease and minimize its impact on tomato production.''')
            treatment = treatment.join('''To effectively manage Tomato Septoria leaf spot, employ a multifaceted approach including cultural practices and chemical interventions. Begin by practicing good sanitation, removing infected plant debris promptly and rotating crops to prevent the buildup of the pathogen in soil. Maintain adequate spacing between plants for proper air circulation, and consider mulching to reduce soil splash. Additionally, apply fungicides containing active ingredients like chlorothalonil or copper hydroxide preventatively or at the first signs of infection, following label instructions carefully to minimize resistance development and environmental impact. Regular monitoring and early detection are crucial for effective control.''')
        elif result == 'Tomato Spider mites Two-spotted spider mite':
            intro = intro.join('''Tomato spider mites, including the notorious two-spotted spider mite (Tetranychus urticae), are among the most damaging pests affecting tomato plants worldwide. These tiny arachnids, barely visible to the naked eye, inflict significant harm by piercing plant cells and feeding on the sap, resulting in yellowing leaves, stippling, and eventually plant death under severe infestations. Two-spotted spider mites are adept at rapid reproduction, often leading to explosive population growth, particularly in warm and dry conditions. Their ability to develop resistance to pesticides further complicates control efforts, posing a significant challenge for tomato growers. Effective management strategies often involve a combination of cultural practices, biological control agents, and selective pesticide applications to mitigate their destructive impact on tomato crops.''')
            treatment = treatment.join('''To effectively manage tomato spider mites, including the two-spotted spider mite, integrated pest management strategies are crucial. Employing cultural practices such as regular monitoring, maintaining plant health through proper watering and fertilization, and reducing dust accumulation can help deter infestations. Introducing natural predators like predatory mites and ladybugs can aid in biological control. When necessary, targeted pesticide applications should be used judiciously, rotating between different chemical classes to minimize the risk of resistance development. Timely intervention and a holistic approach are key to mitigating the damage caused by tomato spider mites while maintaining the health and productivity of tomato crops.''')
        elif result == 'Tomato Target Spot':
            intro = intro.join('''Tomato target spot, caused by the fungal pathogen Corynespora cassiicola, is a prevalent disease affecting tomato plants worldwide. Characterized by circular lesions with dark margins and a lighter center on leaves, fruits, and stems, it poses a significant threat to tomato cultivation, leading to yield losses and quality deterioration. Under favorable environmental conditions such as high humidity and warm temperatures, the pathogen thrives, spreading rapidly and impacting plant health. Effective management strategies including crop rotation, fungicide application, and sanitation practices are crucial for mitigating the impact of tomato target spot and ensuring the sustainability of tomato production.''')
            treatment = treatment.join('''Managing tomato target spot requires a combination of cultural, chemical, and biological control methods. Implementing practices such as crop rotation, maintaining proper spacing between plants, and ensuring adequate airflow can help reduce disease incidence. Fungicides containing active ingredients such as chlorothalonil, azoxystrobin, or copper can be applied preventatively or curatively, following label instructions and local regulations. Additionally, employing resistant tomato varieties and practicing good sanitation by removing infected plant debris can further aid in disease control. Regular monitoring for early signs of target spot and prompt intervention are essential components of an integrated management approach to mitigate its impact on tomato crops.''')
        elif result == 'Tomato Yellow Leaf Curl Virus':
            intro = intro.join('''Tomato Yellow Leaf Curl Virus (TYLCV) is a devastating plant pathogen that poses a significant threat to tomato crops worldwide. Belonging to the Begomovirus genus, it is primarily transmitted by the sweet potato whitefly (Bemisia tabaci). TYLCV infects tomato plants, causing characteristic symptoms such as upward curling and yellowing of leaves, stunted growth, and reduced fruit yield. Its rapid spread, coupled with the lack of effective control measures, makes TYLCV a major concern for tomato growers, leading to substantial economic losses in agriculture.''')
            treatment = treatment.join('''Managing Tomato Yellow Leaf Curl Virus (TYLCV) requires an integrated approach involving cultural, chemical, and genetic strategies. Implementing practices such as crop rotation, controlling whitefly populations through insecticides or biological controls, and utilizing TYLCV-resistant tomato varieties can help mitigate its impact. Additionally, promoting good agricultural practices, such as sanitation and weed control, can further reduce the spread of the virus. Regular monitoring and early detection are crucial for timely intervention, minimizing yield losses and sustaining tomato production in affected areas.''')
        elif result == 'Tomato mosaic virus':
            intro = intro.join('''Tomato mosaic virus (ToMV) is a highly contagious plant pathogen that poses a significant threat to tomato crops worldwide. Belonging to the Tobamovirus genus, ToMV primarily spreads through infected seeds, soil, tools, and mechanical contact, making it challenging to control once established. Symptoms include mosaic patterns on leaves, stunted growth, and reduced fruit yield, ultimately leading to economic losses for farmers. To mitigate its impact, integrated pest management strategies, such as crop rotation and the use of resistant cultivars, are crucial in preventing the spread of ToMV and safeguarding tomato production.''')
            treatment = treatment.join('''Dealing with tomato mosaic virus in plants involves several key steps. Firstly, promptly remove and destroy any infected plants to prevent the spread of the virus. It's crucial to sanitize tools, pots, and any equipment that came into contact with the infected plants to prevent further contamination. Additionally, practicing crop rotation can help minimize the risk of re-infection in future plantings. Utilizing resistant varieties, if available, and implementing proper cultural practices such as adequate spacing, proper watering, and maintaining healthy soil can also aid in preventing the spread of the virus. Finally, if necessary, consider using chemical control methods as recommended by local agricultural extension services, but always follow label instructions carefully to ensure safety and efficacy.''')
        elif result == 'Tomato healthy':
            intro = intro.join('There is no disease in your plant or crop')
            treatment = treatment.join('''Ensuring the health and vitality of plants and crops is paramount for agricultural success. Through a holistic approach that integrates both traditional and innovative methods, we aim to optimize plant growth and resilience. Our treatment regimen begins with soil analysis to determine nutrient deficiencies and pH levels, followed by tailored fertilization strategies. Implementing organic practices, such as composting and crop rotation, enriches soil structure and minimizes reliance on synthetic inputs. We also emphasize pest and disease management through natural predators, companion planting, and eco-friendly sprays. Embracing cutting-edge technologies like precision irrigation and genetic engineering for disease resistance further fortifies our commitment to sustainable agriculture, fostering not only healthier plants but also a thriving ecosystem.''')


        return render_template('index_pred.html', **locals())
if __name__=="__main__":
    app.run(debug=True) 







# Load your trained CNN model and any necessary preprocessing functions here
# For demonstration purposes, I'll use a simple function that always predicts "healthy"


